// -------------------------------------------------------
// myFP2ESP8266 FOCUSER CONFIG
// SPECIFY OPTIONS AND CONTROLLER MODE HERE
// Copyright Robert Brown 2014-2025. All Rights Reserved.
// Copyright Holger M, 2019-2021. All Rights Reserved.
// config.h
// NodeMCU 1.0 (ESP-12E Module)
// -------------------------------------------------------

#ifndef _controller_config_h
#define _controller_config_h

// Caution: Do not enable a feature if the hardware 
// is not fitted on the board. 
// Enable or disable the specific options below

#include <Arduino.h>
#include "boarddefs.h"
#include "defines.h"


// -------------------------------------------------------
// BOARD DEFINES [do not change names]
// -------------------------------------------------------
// Uncomment your board - ONLY ONE BOARD CAN BE UNCOMMENTED

// ESP8266 Boards
//#define DRVBRD    WEMOSDRV8825    // 35.jsn for Holger
//#define DRVBRD    PRO2EDRV8825    // PCB DRV8825  36.jsn
#define DRVBRD    PRO2EULN2003    // PCB ULN2003  38.jsn
//#define DRVBRD    PRO2EL293DNEMA  // 39.jsn
//#define DRVBRD    PRO2EL293D28BYJ48  // 40.jsn
//#define DRVBRD    PRO2EL298N      // 41.jsn
//#define DRVBRD    PRO2EL293DMINI  // 42.jsn
//#define DRVBRD    PRO2EL9110S     // 43.jsn 
//#define DRVBRD    PRO2EDRV8825S   // WeMos D1 R3 + DRV8825  90.jsn
//#define DRVBRD    PRO2EL298NS     // WeMos D1 R3 + L298N 91.jsn
//#define DRVBRD    PRO2EULN2003S   // WeMos D1 R3 + ULN2003 92.jsn
//#define DRVBRD    PRO2EDRV8825DS  // Dev Board + DRV8825 93.jsn
//#define DRVBRD    PRO2EL298NDS    // Dev Board + L298N 94.jsn
//#define DRVBRD    PRO2EULN2003DS  // Dev Board + ULN2003 95.jsn
//#define DRVBRD    CUSTOMBRD       // 99.jsn

// On bootup following a controller firmware update, 
// a default driver board file is created based on 
// your board selection above.


// -------------------------------------------------------
// FIXEDSTEPMODE
// -------------------------------------------------------
// Most boards have a step mode which is hardwired. If the 
// hardwired mode was set to 1/16 step mode then enable 
// FIXEDSTEPMODE to 16.

#define FIXEDSTEPMODE 1
//#define FIXEDSTEPMODE 2
//#define FIXEDSTEPMODE 4
//#define FIXEDSTEPMODE 8
//#define FIXEDSTEPMODE 16
//#define FIXEDSTEPMODE 32


// -------------------------------------------------------
// MOTOR STEPS PER REVOLUTION
// This must be correct for the motor to step properly
// Applicable to the following boards
// -------------------------------------------------------
// stepper motor steps per full revolution using full 
// steps, applies to all boards

#define STEPSPERREVOLUTION  2048  // 28BYJ-48 stepper motor unipolar with ULN2003 board
//#define STEPSPERREVOLUTION  200   // NEMA17 Full-steps
//#define STEPSPERREVOLUTION  400   // NEMA14HM11-0404S 0.9 motor Full-steps
//#define STEPSPERREVOLUTION  1028  // 17HS13-0404S-PG5 Full-steps
//#define STEPSPERREVOLUTION  5370  // NEMA17HS13-0404S-PG27 Full-steps
//#define STEPSPERREVOLUTION  1036  // NEMA14HS13-0804S-PG5 Full-steps
//#define STEPSPERREVOLUTION  1036  // NEMA16HS13-0604S-PG5 Full-steps


// -------------------------------------------------------
// The following CONTROLLER MODES are MUTUALLY EXCLUSIVE 
// and cannot be combined
// LOCALSERIAL,  ACCESSPOINT,  STATION
// -------------------------------------------------------


// -------------------------------------------------------
// CONTROLLER MODE LOCALSERIAL
// -------------------------------------------------------
// remove comment to enable Controller as LOCALSERIAL
//#define CONTROLLERMODE  LOCALSERIAL


// -------------------------------------------------------
// CONTROLLER MODE ACCESSPOINT
// Also, edit defines/accesspoint_defines.h for 
//       ACCESSPOINT TCP/IP values
// Also, edit defines/accesspoint_defines.h for 
//       WiFi SSID and PASSWORD values
// Dependancy: WiFi
// -------------------------------------------------------
// remove comment to enable Controller as ACCESSPOINT
//#define CONTROLLERMODE  ACCESSPOINT


// -------------------------------------------------------
// CONTROLLER MODE STATION
// Also, edit defines/station_defines.h TCP/IP values
// Also, edit defines/station_defines.h 
//       users WiFi login SSID and PASSWORD values
// Also, edit defines/station_defines.h for 
//       station DYNAMICIP or STATICIP
// Dependancy: WiFi
// -------------------------------------------------------
// remove comment to enable Controller as STATION
#define CONTROLLERMODE  STATION

// Enable either DYNAMICIP (default) or STATICIP 
// (1 of them must be enabled)
// IP address is generated by network
#define IPADDRESSMODE  DYNAMICIP

// IP address is specified by this station
//#define IPADDRESSMODE  STATICIP

// To enable reading SSID and PASSWORD from file 
// wificonfig.jsn at boot time, uncomment the 
// following line
#define READWIFICONFIG


// -------------------------------------------------------
// SERVERS
// ALPACA SERVER is required for Dynamic clients
// TCPIP SERVER is required for Windows+ASCOM+LINUX+INDI apps
// Dependancy: WiFi
// -------------------------------------------------------
// To enable ALPACA SERVER uncomment the following line
#define ENABLE_ALPACASERVER  1

// To enable TCP/IP SERVER uncomment the following line
#define ENABLE_TCPIPSERVER  2

// To enable WEB SERVER uncomment the following line
#define ENABLE_WEBSERVER  3


// --------------------------------------------------------
// MDNS
// See defines/app_defines.h
// Dependancy: WiFi
// --------------------------------------------------------
// To enable MDNS uncomment next line
#define ENABLE_MDNS

// MDNS_NAME must be lowercase and limited to 12 characters
// Alphanumeric (0..9, a..z)


// --------------------------------------------------------
// POWERDOWN DISPLAY
// Turns off
// Display
// once elapsed time internal expires
// --------------------------------------------------------
// To enable POWERDOWN uncomment the following line
#define ENABLE_PWRDOWN


// -------------------------------------------------------
// TEMPERATURE PROBE
// -------------------------------------------------------
// To enable the TEMPERATURE PROBE uncomment the 
// following line
// #define ENABLE_TEMPERATUREPROBE


// -------------------------------------------------------
// TEXT DISPLAY (0.96" 8-line display) 
// DRIVER TYPE (SSD1306)
// Library myOLED
// -------------------------------------------------------
// #define DISPLAYTYPE   TEXT_OLED12864


// -------------------------------------------------------
// GRAPHICS DISPLAY (1.3" 128*64) 
// DRIVER TYPE (SSH1106)
// https://github.com/ThingPulse/esp8266-oled-ssd1306
// -------------------------------------------------------
//#define DISPLAYTYPE   GRAPHIC_OLED12864


// -------------------------------------------------------
// DUCKDNS
// If not using DuckDNS, then editing this file is DONE
// See defines/duckdns_defines.h for more settings
// Dependancy: WiFi
// -------------------------------------------------------
// To use DUCKDNS uncomment the next line
// #define ENABLE_DUCKDNS 1


// -------------------------------------------------------
// DO NOT CHANGE
// CHECK BOARD AND HARDWARE OPTIONS
// -------------------------------------------------------
// DRVBRD must be defined
#ifndef DRVBRD
#error "ERROR: DRVBRD NOT DEFINED"
#endif

#ifndef CONTROLLERMODE
#error "ERROR: CONTROLLERMODE not set. Should be LOCALSERIAL or ACCESSPOINT or STATION"
#endif

#if (CONTROLLERMODE == STATION)
#if !defined(IPADDRESSMODE)
#error "ERROR: IPADDRESSMODE HAS NOT BEEN ENABLED FOR STATION"
#endif
#endif


#if (CONTROLLERMODE == LOCALSERIAL)
#if !defined(IPADDRESSMODE)
#define IPADDRESSMODE  SERIALIP
#endif
#if defined(ENABLE_ALPACASERVER)
#error "ERROR: LOCALSERIAL mode does not support ENABLE_ALPACASERVER"
#endif
#if defined(ENABLE_TCPIPSERVER)
#error "ERROR: LOCALSERIAL mode does not support ENABLE_TCPIPSERVER"
#endif
#if defined(ENABLE_WEBSERVER)
#error "ERROR: LOCALSERIAL mode does not support ENABLE_WEBSERVER"
#endif
#if defined(ENABLE_DUCKDNS)
#error "ERROR: LOCALSERIAL mode does not support ENABLE_DUCKDNS"
#endif
#endif


// cannot run Duckdns with ACCESSPOINT
#if (CONTROLLERMODE == ACCESSPOINT)
#if !defined(IPADDRESSMODE)
#define IPADDRESSMODE  ACCESSPOINTIP
#endif
#if defined(ENABLE_DUCKDNS)
#error "ERROR: DUCKDNS only works with STATION"
#endif
#endif

#if defined(ENABLE_MDNS)
#if !defined(ENABLE_WEBSERVER)
#error "ERROR: MDNS REQUIRES WEBSERVER TO BE ENABLED"
#endif
#endif

#endif
